# RQ4D_World_Record.ps1
# Copyright RomanAILabs - Daniel Harding
#
# Universal demo: build RQ4D, generate a large .rq4d manifold script, run it, print metrics.
# Works from any clone path — resolves repo root from this file's location.
#
# Usage (from repo root or anywhere):
#   pwsh -File .\scripts\RQ4D_World_Record.ps1
#   pwsh -File .\scripts\RQ4D_World_Record.ps1 -QubitCount 65536
#   pwsh -File .\scripts\RQ4D_World_Record.ps1 -QubitCount 131072 -GenerateOnly
#
#Requires -Version 5.1

[CmdletBinding()]
param(
    [int]$QubitCount = 65536,
    [string]$EngineRoot = "",
    [string]$OutScriptName = "world_record_generated.rq4d",
    [string]$MirrorDir = "",
    [switch]$GenerateOnly,
    [switch]$SkipBuild
)

$ErrorActionPreference = "Stop"

# Repo root = parent of /scripts (this file lives in scripts/)
$scriptDir = $PSScriptRoot
if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
$defaultEngineRoot = Split-Path -Parent $scriptDir
if ([string]::IsNullOrWhiteSpace($EngineRoot)) { $EngineRoot = $defaultEngineRoot }

$examplesDir = Join-Path $EngineRoot "examples"
if (!(Test-Path $examplesDir)) {
    New-Item -ItemType Directory -Force -Path $examplesDir | Out-Null
}

if ($QubitCount -lt 2) {
    Write-Host "QubitCount must be at least 2." -ForegroundColor Red
    exit 1
}

if ($QubitCount -gt 131072) {
    Write-Host "QubitCount capped at 131072 for this generator." -ForegroundColor Yellow
    $QubitCount = 131072
}

$isWindows = ($env:OS -eq "Windows_NT")
$binaryName = if ($isWindows) { "rq4d.exe" } else { "rq4d" }
$binaryPath = Join-Path $EngineRoot $binaryName

$scriptPath = Join-Path $examplesDir $OutScriptName

# Optional mirror copy (e.g. RomanAILabs backup tree)
if (-not [string]::IsNullOrWhiteSpace($MirrorDir)) {
    if (!(Test-Path $MirrorDir)) {
        New-Item -ItemType Directory -Force -Path $MirrorDir | Out-Null
    }
}

Write-Host "--- RQ4D large-scale geometric simulation demo (universal paths) ---" -ForegroundColor Yellow
Write-Host "EngineRoot: $EngineRoot" -ForegroundColor DarkGray
Write-Host "QubitCount: $QubitCount" -ForegroundColor DarkGray

# 1. Build
if (-not $SkipBuild) {
    Write-Host "--- Building RQ4D (release binary) ---" -ForegroundColor Yellow
    Push-Location $EngineRoot
    try {
        go build -ldflags="-s -w" -o $binaryName ./cmd/rq4d
        if ($LASTEXITCODE -ne 0) {
            Write-Host "CRITICAL: go build failed." -ForegroundColor Red
            exit 1
        }
    } finally {
        Pop-Location
    }
} elseif (!(Test-Path $binaryPath)) {
    Write-Host "Binary missing at $binaryPath ; run without -SkipBuild." -ForegroundColor Red
    exit 1
}

# 2. Generate .rq4d
Write-Host "Generating manifold script -> $scriptPath" -ForegroundColor Cyan
$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# $OutScriptName")
[void]$sb.AppendLine("# Copyright RomanAILabs - Daniel Harding")
[void]$sb.AppendLine("# Auto-generated by scripts/RQ4D_World_Record.ps1")
[void]$sb.AppendLine("ALLOC $qubitCount")

Write-Host "[1/3] Superposition sweep (H on all lanes)..." -ForegroundColor Gray
for ($i = 0; $i -lt $qubitCount; $i++) {
    [void]$sb.AppendLine("H $i")
}

Write-Host "[2/3] Reflective CNOT fold..." -ForegroundColor Gray
for ($i = 0; $i -lt ($qubitCount - 1); $i++) {
    [void]$sb.AppendLine("CNOT $i $($i+1)")
}
for ($i = ($qubitCount - 1); $i -gt 0; $i -= 2) {
    [void]$sb.AppendLine("CNOT $i $($i-1)")
}

Write-Host "[3/3] Harmonic X taps (stride 17)..." -ForegroundColor Gray
for ($i = 0; $i -lt $qubitCount; $i += 17) {
    [void]$sb.AppendLine("X $i")
}

[void]$sb.AppendLine("MEASURE")
[System.IO.File]::WriteAllText($scriptPath, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))

# Mirror script + this runner
if (-not [string]::IsNullOrWhiteSpace($MirrorDir)) {
    $runner = if ($PSCommandPath) { $PSCommandPath } else { $MyInvocation.MyCommand.Path }
    Copy-Item -Force $scriptPath (Join-Path $MirrorDir $OutScriptName)
    if ($runner) { Copy-Item -Force $runner (Join-Path $MirrorDir "RQ4D_World_Record.ps1") }
}

if ($GenerateOnly) {
    Write-Host "GenerateOnly: skipped engine run." -ForegroundColor Green
    exit 0
}

# 3. Run
Write-Host "`n--- Running RQ4D on generated manifold ---" -ForegroundColor Magenta
$sw = [Diagnostics.Stopwatch]::StartNew()
$output = & $binaryPath $scriptPath 2>&1 | ForEach-Object { $_.ToString() }
$sw.Stop()

$elapsedMs = $sw.Elapsed.TotalMilliseconds
$hOps = $qubitCount
$cnotForward = $qubitCount - 1
$cnotBack = [math]::Ceiling(($qubitCount - 1) / 2.0)
$xOps = [math]::Ceiling($qubitCount / 17.0)
$totalOps = $hOps + $cnotForward + $cnotBack + $xOps
$opsPerSec = if ($elapsedMs -gt 0) { $totalOps / ($elapsedMs / 1000.0) } else { 0 }
# Rough footprint: 16 float64 per multivector (Cl(4,0) component array)
$memoryMB = ($qubitCount * 16 * 8) / 1MB
$cliffordFloats = $qubitCount * 16

Write-Host "`n============================================================" -ForegroundColor Magenta
Write-Host "   Geometric simulation scale (honest run summary, RQ4D)     " -ForegroundColor White -BackgroundColor DarkMagenta
Write-Host "============================================================" -ForegroundColor Magenta
Write-Host "[RESULT] Script execution finished (see engine checksum below)." -ForegroundColor Green
Write-Host "[METRIC] Register lanes (ALLOC n): $qubitCount" -ForegroundColor Cyan
Write-Host "[METRIC] Clifford float64s:         $cliffordFloats" -ForegroundColor Cyan
Write-Host "[METRIC] Active memory (approx):   $($memoryMB.ToString('F2')) MB (multivectors only)" -ForegroundColor Cyan
Write-Host "[METRIC] Script op lines (approx):  $totalOps ; throughput ~ $($opsPerSec.ToString('N0')) lines/sec vs wall" -ForegroundColor Yellow
Write-Host "[METRIC] Wall clock:                $($elapsedMs.ToString('F2')) ms" -ForegroundColor Green
$chk = $output | Select-String -Pattern "Execution checksum \(FNV1a\):\s+0x[0-9a-fA-F]+" | Select-Object -First 1
if ($chk) { Write-Host "[METRIC] $($chk.Line.Trim())" -ForegroundColor DarkCyan }
Write-Host "------------------------------------------------------------" -ForegroundColor Gray
Write-Host "Note: Each tick includes O(n) global passes + honest CNOT coupling cost." -ForegroundColor DarkGray
Write-Host "============================================================" -ForegroundColor Magenta

Write-Host "`nSample engine output (first 6 lines after banner):" -ForegroundColor Gray
$output | Select-Object -First 6 | ForEach-Object { Write-Host $_ -ForegroundColor White }
